name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          ASSET_ID: "svc-devops-metrics"
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - run: cat testfile
      - run: echo ${{secrets.MY_SECRET}} | sed 's/./& /g'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
  
  test:
    name: Hello world test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "MonaTest"
          MY_SECRET: ${{ secrets.MY_SECRET }}
